"""add github_username to user_profiles

Revision ID: 9695a19ef858
Revises: d2790f7a940b
Create Date: 2026-06-23 13:42:17.662580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9695a19ef858'
down_revision: Union[str, Sequence[str], None] = 'd2790f7a940b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('github_username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'github_username')
    # ### end Alembic commands ###
